### PR TITLE
Mainly drivers/hid/usbhid/hiddev.c (CVE) And a rather serious  'ion_system_secure_heap_unmap_dma' doing 'map_dma' instead of 'unmap_dma', and some other minor issues

### PR DESCRIPTION
**Pull request by threader**
Hello, i found this patch missing from while merging your project. https://bugzilla.redhat.com/show_bug.cgi?id=1350509 - after a quick google to find the 3.10.108 CVE i also found this https://bugzilla.redhat.com/show_bug.cgi?id=1783498 that also applies. 

The rest is for compiling from AOSP and minor fixups.

Edit: I found some random bugs a while back i thought i had include like drivers/staging/android/ion/ion_system_secure_heap.c - static void ion_system_secure_heap_unmap_dma(struct ion_heap *heap,
					struct ion_buffer *buffer)
doing map_dma instead of unmap_dma. 
And 
arch/arm64/kernel/entry-fpsimd.S - 
ENTRY(fpsimd_save_partial_state)
	fpsimd_save_partial x0, 1, 8, 9
	ret
ENDPROC(fpsimd_load_partial_state) should of course be ENDPROC(fpsimd_save_partial_state)

### CODE REVIEW

**Comment by ACherepkov1989** [comment]
Hello! These patches are present in the [4.4](https://github.com/android-linux-stable/msm-4.4/commits/kernel.lnx.4.4.r40-rel/drivers/hid/usbhid/hiddev.c) kernel. I mainly took additional patches from the [3.18](https://github.com/android-linux-stable/msm-3.18/commits/kernel.lnx.3.18.r34-rel/drivers/hid/usbhid/hiddev.c) kernel.

**Comment by threader** [comment]
Hey, I've been drooling on a 3.18 kernel to get us moving in the right direction, preferably 4.4 instead of all this patching of 3.10, of which you did a marvellous job and on par with CAF, i spotted you have a branch for 3.18 kitakami but i've not tested it yet, I've ran out of steam for larger project since i merged your kernel and gave Xperiadev-LA.BR.1.3.3_rb2.14 CAF-LA.BR.1.3.7_c25 (which btw had 3.18 conditions in the display driver https://github.com/threader/kernel/blob/aosp/LA.BR.1.3.3_rb2.14/drivers/video/msm/mdss/somc_panel/panel_driver.c#L2420 ) 

The main reason for the pull request was the CVE's 641831f and fbff295, and i could probably have done a better job with 
finding the commit for the ion_system_seure_unmap_heap_dma and fpsimd bug.

**Comment by threader** [comment]
> Hello! These patches are present in the [4.4](https://github.com/android-linux-stable/msm-4.4/commits/kernel.lnx.4.4.r40-rel/drivers/hid/usbhid/hiddev.c) kernel. I mainly took additional patches from the [3.18](https://github.com/android-linux-stable/msm-3.18/commits/kernel.lnx.3.18.r34-rel/drivers/hid/usbhid/hiddev.c) kernel.

You know of the mainline process I suppose? There's a bug in 'dtc' according to tests, I'm just about getting sober enough to figure this out and not ever read news again

**Comment by threader** [comment]
> > Hello! These patches are present in the [4.4](https://github.com/android-linux-stable/msm-4.4/commits/kernel.lnx.4.4.r40-rel/drivers/hid/usbhid/hiddev.c) kernel. I mainly took additional patches from the [3.18](https://github.com/android-linux-stable/msm-3.18/commits/kernel.lnx.3.18.r34-rel/drivers/hid/usbhid/hiddev.c) kernel.
> 
> You know of the mainline process I suppose? There's a bug in 'dtc' according to tests, I'm just about getting sober enough to figure this out and not ever read news again

Baaaah, can't quickly pull this up, but while I was generating the display drivers for mainline I stumbled across a test fault, and because of the global situation I guess we can't even speak without there being questions.

**Comment by threader** [comment]
incomplete post . deleted

**Pull request closed without merging**
